### ISSUE TITLE
Explanation of currently supported types?

### ISSUE THREAD

**Issue by thenickcox** [Hacker-007/envious#31]
First, this project is super exciting!

I'd love to see an explanation of supported types pretty high up in the readme. As this project is influenced by Rust, it's notable that the [landing page of the docs](https://doc.rust-lang.org/std/) features all of the supported types.

Fully going on opinion here, but that's also a good way to grok what a language is about. For example, if you come to a language like Go from a language like Ruby or JavaScript, one of the first unique aspects you're likely to come across is [the difference between a string and a byte array](https://yourbasic.org/golang/convert-string-to-byte-slice/#:~:text=Performance-,Basics,byte%20slices%20can%20be%20modified.).

So like, when I first come to a language, the first thing I do is decide what are going to be the mind-bending aspects of the learning curve, and types give a hint in that regard.

For me, it's like this. With Rust, that's borrowing. With Go, it's the lack of generics. With Haskell, it's that there's no `NULL`. 

So what's going to blow my mind about Envious?

**Comment by thenickcox** [comment]
Or maybe that's its selling point? There's nothing mind-warping about it, and its familiarity is a feature? That'd also be awesome!

**Comment by Hacker-007** [comment]
I took some time to think about the exact distinctions and here is the list that I have come up (though most of these distinctions aren't implemented yet):
- Simple to write and understand (almost as easy as Python if not easier)
- Expressive in nature (should have the ability to write powerful code in a concise manner)
- Should be fast (the outputted binary should be extremely fast)

I think, for now, these three basic tenets are reasonable and shoot for a language that is like Rust but with fewer constraints.

Do you have any suggestions as to what I can add to this list?
